language: d

sudo: false

d:
  - dmd
  - ldc

script:
  - dub test --compiler=$DC || exit 1

before_install:
  - openssl aes-256-cbc -K $encrypted_4146233f44f9_key -iv $encrypted_4146233f44f9_iv
    -in travisci.rsa.enc -out travisconfig/travisci.rsa -d
  - chmod 0600 travisconfig/travisci_rsa
  - cp travisconfig/travisci_rsa ~/.ssh/id_rsa
  - ./createddox.sh
